type Lyric = {
  delay: number;
  text: string;
  newLine: boolean;
  clear: boolean;
};

export const lyrics: Lyric[] = [
  {
    delay: 4.2,
    text: "Forms FORM-29827281-12-2:",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.0,
    text: "Notice of Dismissal",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.8,
    text: "Well here we are again",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.6,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.98,
    text: "It's always such a pleasure",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.6,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.43,
    text: "Remember when you tried",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.34,
    text: "to ",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.82,
    text: "kill me twice?",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.1,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.8,
    text: "Oh how we laughed and laughed",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.3,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 2.0,
    text: "Except I wasn't laughing",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.5,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.69,
    text: "Under the",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.49,
    text: " circumstances",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.81,
    text: "I've been ",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.26,
    text: "shockingly ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.33,
    text: "nice",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.9,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.3,
    text: "",
    newLine: false,
    clear: true,
  },
  {
    delay: 2.12,
    text: "You want your freedom?",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.2,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.0,
    text: "Take it",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.98,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.7,
    text: "That's what I'm counting on",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.5,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.95,
    text: "I used to ",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.13,
    text: "want you ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.73,
    text: "dead",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.3,
    text: "but ",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.39,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.4,
    text: "Now I only ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.922,
    text: "want you ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.7,
    text: "gone",
    newLine: true,
    clear: false,
  },
  {
    delay: 3.6,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.9,
    text: "",
    newLine: true,
    clear: true,
  },
  {
    delay: 1.741,
    text: "She was a lot like you",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.8,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.858,
    text: "(Maybe not quite as heavy)",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.65,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.5,
    text: "Now little Caroline ",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.9,
    text: "is in here too",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.9,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.985,
    text: "One day they woke me up",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.51,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 2.12,
    text: "So I could live forever",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.2,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.75,
    text: "It's such a shame the same",
    newLine: true,
    clear: false,
  },
  {
    delay: 3.19,
    text: "will never happen to you",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.5,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: false,
    clear: true,
  },
  {
    delay: 0.09,
    text: "Severance Package Details:",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.88,
    text: "You've got your",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.25,
    text: "short sad",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.69,
    text: "life ",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.5,
    text: "left",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.48,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.5,
    text: "That's what I'm counting on",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.1,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 3.29,
    text: "I'll let you get right to it",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.3,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.4,
    text: "Now I only ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.922,
    text: "want you ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.7,
    text: "gone",
    newLine: false,
    clear: false,
  },
  {
    delay: 3.968,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.1,
    text: "",
    newLine: false,
    clear: true,
  },
  {
    delay: 1.77,
    text: "Goodbye my only friend",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.62,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.24,
    text: "Oh,",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.383,
    text: " ",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.34,
    text: "did you think I meant you?",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.57,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.16,
    text: "That would be funny",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.38,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.95,
    text: "if it weren't ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.905,
    text: "so sad",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.21,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.79,
    text: "Well you have been replaced",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.61,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 2.08,
    text: "I don't need anyone now",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.24,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 2.02,
    text: "When I delete you maybe",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.1,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 2.5,
    text: "[REDACTED]",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.7,
    text: "",
    newLine: true,
    clear: true,
  },
  {
    delay: 0.3,
    text: "",
    newLine: true,
    clear: true,
  },
  {
    delay: 1.567,
    text: "Go make some new ",
    newLine: false,
    clear: false,
  },
  {
    delay: 2.02,
    text: "disaster",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.27,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.5,
    text: "That's what I'm counting on",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.15,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 3.36,
    text: "You're someone else's problem",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.35,
    text: "Now I only want you ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.1,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.16,
    text: "gone",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.18,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 2.358,
    text: "Now I only want you ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.1,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.16,
    text: "gone",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.15,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.88,
    text: "Now I only want ",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.57,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.3,
    text: "you",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.3,
    text: "",
    newLine: true,
    clear: true,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.16,
    text: "gone",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.3,
    text: "",
    newLine: false,
    clear: true,
  },
  {
    delay: 0.01,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: false,
    clear: false,
  },
  {
    delay: 1.16,
    text: "portal 2 - want you gone ",
    newLine: true,
    clear: false,
  },
  {
    delay: 3.21,
    text: "made in Solid by Gurkan (https://gurkz.me) ",
    newLine: true,
    clear: false,
  },
  {
    delay: 3.21,
    text: "source code is available on https://github.com/thatgurkangurk/gurkz.me ",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 3.21,
    text: "Copyright 2011- Valve Corporation.",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.21,
    text: "All Rights Reserved",
    newLine: true,
    clear: false,
  },
  {
    delay: 3.21,
    text: "Valve, Steam, Portal 2 are trademarks and/or registered trademarks of",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.21,
    text: "Valve Corporation. ",
    newLine: true,
    clear: false,
  },
  {
    delay: 1.21,
    text: "All other trademarks are property of their respective owners.",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.21,
    text: "For the full legal info please refer to",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.21,
    text: "https://store.steampowered.com/legal ",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 0.01,
    text: "",
    newLine: true,
    clear: false,
  },
  {
    delay: 2.21,
    text: "thank you for watching <3 ",
    newLine: true,
    clear: false,
  },
];
