services:
  database:
    image: postgres:17.2-alpine
    volumes:
      - gurkzme-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gurkz
      POSTGRES_PASSWORD: LOCAL_PASSWORD
      POSTGRES_DB: gurkz
    ports:
      - "5432:5432"

volumes:
  gurkzme-postgres: