allowBuilds:
  esbuild: true
  ffmpeg-static: true
minimumReleaseAgeExclude:
  - vite@8.2.0
  - "@thatgurkangurk/awty@0.4.0 || 0.5.0 || 0.6.0 || 0.7.0 || 0.7.1"
patchedDependencies:
  runed@0.37.1: patches/runed@0.37.1.patch
