minimumReleaseAgeExclude:
  - '@orpc/client@2.0.0-beta.33'
  - '@orpc/contract@2.0.0-beta.33'
  - '@orpc/json-schema@2.0.0-beta.33'
  - '@orpc/openapi@2.0.0-beta.33'
  - '@orpc/server@2.0.0-beta.33'
  - '@orpc/shared@2.0.0-beta.33'
  - '@orpc/tanstack-query@2.0.0-beta.33'
  - '@standardserver/aws-lambda@0.8.3'
  - '@standardserver/core@0.8.3'
  - '@standardserver/fastify@0.8.3'
  - '@standardserver/fetch@0.8.3'
  - '@standardserver/node@0.8.3'
  - '@standardserver/peer@0.8.3'
  - '@standardserver/shared@0.8.3'
