name: Linting and formatting checks

on:
    pull_request:
        branches: [main]

    workflow_dispatch:

    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    eslint:
        name: ESLint
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun i --frozen-lockfile -D
            - name: Check linting with ESLint
              run: bun run eslint:check
    prettier:
        name: Prettier
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun i --frozen-lockfile -D
            - name: Check formatting with Prettier
              run: bun run prettier:check
